### ISSUE TITLE
I think the plugin may need to be updated

### ISSUE THREAD

**Issue by ProsperCraft** [hsyyid/PayDay#1]
I have EconomyLite 1.2.1, and spongeforge-1.8.9-1763-4.1.0-BETA-1212.jar

and I get this in console, players don't get paid.

http://pastebin.com/PeNSRbYm

**Comment by hsyyid** [comment]
I'll do it today

**Comment by ProsperCraft** [comment]
Bump :)

**Comment by hsyyid** [comment]
@ProsperCraft OMG I totally forgot! Sooo sorry

**Comment by hsyyid** [comment]
Closed in 6a76006882d213f8069586982d3748e60ca83e78
