### ISSUE TITLE
Could you update it again?

### ISSUE THREAD

**Issue by 5igm** [hsyyid/PayDay#2]
Hello? Do you still develop this one? I think may it is better to update the plugin to the latest sponge api 4.xx and 5.xx.

**Comment by 5igm** [comment]
I think PayDay cannot work in the latest sponge, and could you add more specific commands or permissions? I want to know what should I do if I don't use PEX.

**Comment by 5igm** [comment]
In addition, May you make a configuaration file for the plugin? I also suggest to add an option of maximum money a player can earn per day.

**Comment by ProsperCraft** [comment]
http://pastebin.com/airYPwFk

Is this because it doesn't support the 5.0 API?

**Comment by 5igm** [comment]
Yes, it doesn't work well in 5.0 API @ProsperCraft

**Comment by 5igm** [comment]
Moreover, could make it more compatible with other permission plugins and add the option of maximum amount of money a person can get per day?
