### ISSUE TITLE
Please build a 5.0 api version.

### ISSUE THREAD

**Issue by ProsperCraft** [hsyyid/PayDay#4]

**Comment by crymates** [comment]
Yep, true story. Please update it to API 5, it gives an exception currently and does not pay.

**Comment by ProsperCraft** [comment]
There is an unofficial build you can find in the plugin thread that we are using and it works.

**Comment by crymates** [comment]
Do you have an link?

**Comment by crymates** [comment]
Finally found what you mean. How to build an jar-file from the master branch?

**Comment by crymates** [comment]
Got it, but server crashs with new 0.6 jar :/

**Comment by ProsperCraft** [comment]
It works for me, did you update to the latest spongeforge?

**Comment by crymates** [comment]
I cannot upgrade to newest one, because I use alot of plugins on my server :] Not everyone is compatible with newest sponge version.
