### ISSUE TITLE
Request for MC 1.12?     API 7?

### ISSUE THREAD

**Issue by Wissi** [hsyyid/PayDay#8]
We love the plugin and have been using it quite a lot. 
Will you be porting it over to 1.12? 
We have a server already running Sponge 1.12 and want to keep using your great plugin.

I think in the past you had given us a Jenkins link(?), but can't seem to find it.

**Comment by hsyyid** [comment]
Hello,

This plugin was forked and is maintained by @Flibio

Please contact him for any support

https://ore.spongepowered.org/Flibio/PayDay
